### ISSUE TITLE
The calculator is not responsive

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/calculator#1]
The calculator code currently is suitable for desktop devices, and not suitable for mobile view.

Try to make it better

**Comment by ppfeiler** [comment]
Hi! Would it be okay to add [vite](https://vitejs.dev/) to this project? With that we could add support for scss which would really help in writing responsive styles.

**Comment by subhranshuchoudhury** [comment]
i can make it responsive. will you assign this to me ?

**Comment by DhanushNehru** [comment]
You can use anything which you are comfortable in doing @subhranshuchoudhury

**Comment by sauravsilawat** [comment]
Hi @DhanushNehru, I would like to work on this, Can I?

**Comment by subhranshuchoudhury** [comment]
> Hi @DhanushNehru, I would like to work on this, Can I?

I am already on this. And it is in final stage.

**Comment by ppfeiler** [comment]
@subhranshuchoudhury are you adding npm and some build system?

**Comment by subhranshuchoudhury** [comment]
> @subhranshuchoudhury are you adding npm and a build system? Please dont just use the bootstrap cdn. 
> 
> As i wrote some comments above, I already started on this. 
> 
> If you like, I can push my build system and npm work and you can add the new responsible bootstrap layout. 
> 
> @DhanushNehru please dont assign multiple people on the same issue.

I already raised PR. i just used bootstrap for the Accordion. I didn't use npm.

**Comment by DhanushNehru** [comment]
Hi @subhranshuchoudhury the calculator viewed on mobile is fine

But in desktop view it should be viewed 

like this

<img width="773" alt="Screenshot 2022-10-05 at 1 15 39 PM" src="https://user-images.githubusercontent.com/22955675/194007693-520d9078-3cfc-405b-beb7-11621e27064a.png">

and not like this

<img width="1402" alt="Screenshot 2022-10-05 at 1 14 26 PM" src="https://user-images.githubusercontent.com/22955675/194007593-a80ebd32-444b-4ca9-8d1b-ca555d0b8e41.png">

**Comment by subhranshuchoudhury** [comment]
Ok i will fix it
