### ISSUE TITLE
Add option to share this site in social media

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/calculator#100]
Need option to share this calculator site in social media

**Comment by JAHANVI128** [comment]
@DhanushNehru I want to work on this issue...can you assign me?

**Comment by DhanushNehru** [comment]
Sure @JAHANVI128

**Comment by om453** [comment]
Hello @DhanushNehru  pls assign me this i want to work on this

**Comment by DhanushNehru** [comment]
@om453 , I guess @JAHANVI128 is already working on it
