### ISSUE TITLE
Make the calculator responsive

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/calculator#102]
The calculator when viewed in mobile is not as responsive as expected

Please add before & after screenshots of you are contributing to this issue

**Comment by bishwobista** [comment]
assign me

**Comment by DhanushNehru** [comment]
Hi @bishwobista  currently it is responsive but I want it more better User Experience, especially the share button etc.

Assigning to you

**Comment by sanathan-git** [comment]
Hlo Dhanush can you please check the my pr related Calculator responsiveness (◕‿◕)
