### ISSUE TITLE
Input field not clearing after calculation 

### ISSUE THREAD

**Issue by aj12-houdini** [DhanushNehru/calculator#112]
### Issue: Input field not clearing
Whenever a calculation is performed, the result gets displayed on the calculator screen, and when the user goes to type in a new number, the input field does not reset to blank with the new number, instead, it adds to the result of the previous calculation. I think that should be fixed for user convenience like a real calculator.

**Comment by JeevaRamanathan** [comment]
I would like to work on this Issue, pls assign

**Comment by DhanushNehru** [comment]
Do you want to work on this @aj12-houdini

**Comment by aj12-houdini** [comment]
> Do you want to work on this @aj12-houdini 

Yeah I would love to

**Comment by ashmichheda** [comment]
Hi @DhanushNehru - I would like to work on this issue. Can you assign it to me?
