### ISSUE TITLE
Calculation error: 0.6 + 0.3 results in 0.8999999999999999

### ISSUE THREAD

**Issue by JeevaRamanathan** [DhanushNehru/calculator#117]
0.6 + 0.3 should be 0.9, but it is returning 0.8999999999999999 instead. 
This issue is not specific to the calculation 0.6 + 0.3 = 0.9, but rather a consequence of the way floating-point numbers are represented in JavaScript

@DhanushNehru I would like to work on this.

**Comment by shivansh84ya** [comment]
is this issue is still active??

**Comment by DhanushNehru** [comment]
No @shivansh84ya

**Comment by JeevaRamanathan** [comment]
No @shivansh84ya, it's solved!
