### ISSUE TITLE
New feature - Erase button to erase the digits

### ISSUE THREAD

**Issue by arunkarthicknm** [DhanushNehru/calculator#13]
The calculator is in need of erase button. :)
If you find this as relevant, assign me, I can do it:)

**Comment by DhanushNehru** [comment]
Yes an eraze button, to remove digit by digit

You can do this, but make sure the position of new button is justifiable if created @arunkarthicknm

**Comment by DhanushNehru** [comment]
https://github.com/DhanushNehru/calculator/pull/12
