### ISSUE TITLE
Optimize nCr calculation using DP

### ISSUE THREAD

**Issue by siddxharth1** [DhanushNehru/calculator#133]
The current implementation of calculating combinations  nCr using factorials is inefficient for large values of n and r. Factorial calculations for large numbers issues Uncaught RangeError: Maximum call stack size exceeded
I would like to resolve this issue.

**Comment by BYT-Bender** [comment]
Can you assigned me this issue.

**Comment by siddxharth1** [comment]
@BYT-Bender i am working on it !
