### ISSUE TITLE
Printing digits twice on a single keyboard press.

### ISSUE THREAD

**Issue by Umesh2202** [DhanushNehru/calculator#15]
Hello @DhanushNehru 

On a single number key press the digit is printed twice on the screen. I have fixed the issue.

Please assign this issue to me.

Thank you 😄

**Comment by CodeVibranium** [comment]
@DhanushNehru , is this still open?

**Comment by DhanushNehru** [comment]
It is resolved @CodeVibranium

**Comment by CodeVibranium** [comment]
> 

@DhanushNehru , please let me know if there are issues to fix.

**Comment by DhanushNehru** [comment]
You can check the issues tab @CodeVibranium
