### ISSUE TITLE
UI Enhancement - Alert when clicking on Solve Equation button without giving any equation  - Changing the alert a Toast Message

### ISSUE THREAD

**Issue by MohammedJunaid02** [DhanushNehru/calculator#154]
Hi @DhanushNehru ,
When we click on Solve Equation button which entering any equation then we get this error.

![image](https://github.com/user-attachments/assets/d37272f3-6d16-4420-883d-a917f1276a81)

So i want to change it to a Toast Message.
I will keep the UI which i have resolved for Delete History only.
Please assign this to me.

Thank You

**Comment by MohammedJunaid02** [comment]
@DhanushNehru , assign this Hacktober Fest label, feature enhancement labels

**Comment by MohammedJunaid02** [comment]
@DhanushNehru , assign this Hacktober Fest label, feature enhancement labels

**Comment by MohammedJunaid02** [comment]
Hey @DhanushNehru ,

I have raised the PR for this issue, Please review it once and merge it.

PR Link : https://github.com/DhanushNehru/calculator/pull/160

FYI, I have done some unit testing as well

Thank You

**Comment by MohammedJunaid02** [comment]
Also @DhanushNehru ,
This will be the final look for the Toast Message, Please have a look


https://github.com/user-attachments/assets/aab33184-9d38-44c9-95af-dd85e2f1bca2

**Comment by DhanushNehru** [comment]
Looks great @MohammedJunaid02
