### ISSUE TITLE
Improve the output screen of the calculator

### ISSUE THREAD

**Issue by surya-doc** [DhanushNehru/calculator#41]
![image](https://user-images.githubusercontent.com/69008196/194098770-bef67b49-26be-49f8-baf5-437989a5cc9d.png)
* The small screen and text of the output screen make it difficult for the user to calculate.
* At the same time the keyboard keys are quite big.
Want to work on this issue to improve the UI of the screen.

**Comment by CraveforSuccess** [comment]
I can help you out on this, kindly assign me this task

**Comment by DhanushNehru** [comment]
@surya-doc close this issue if completed
