### ISSUE TITLE
Repetition of " . " when clicked multiple times

### ISSUE THREAD

**Issue by BasharVI** [DhanushNehru/calculator#58]
The " . " is repeated when it is pressed multiple times. It should not repeat if pressed multiple times 
@DhanushNehru please assign this to me

**Comment by BasharVI** [comment]
hi @DhanushNehru could you add tags and labels to this issue and assign me to work on this?

**Comment by shouryakhanka** [comment]
Hey @DhanushNehru if this issue has not been resolved yet, can i work on this ?

**Comment by selemondev** [comment]
This issue has finally been resolved . Thank you to everyone who contributed ✨
