### ISSUE TITLE
Adding feature: Calculator history

### ISSUE THREAD

**Issue by subhranshuchoudhury** [DhanushNehru/calculator#61]
1. save calculator history in local storage.
2. where user can see previous entries.
3. Tools: Local Storage

Assign me this work and add **hacktoberfest** label. @DhanushNehru

**Comment by NishakarKT** [comment]
May I take this one?

**Comment by subhranshuchoudhury** [comment]
@DhanushNehru please add hacktoberfest label to this issue.
