### ISSUE TITLE
isInteger is not defined: Uncaught ReferenceError: isInteger is not defined

### ISSUE THREAD

**Issue by subhranshuchoudhury** [DhanushNehru/calculator#64]
* the function which declared inside script.js is not defined.

**Comment by Ladam0203** [comment]
Hey, can I work on this? Should I just define the method inside the script.js?

**Comment by subhranshuchoudhury** [comment]
Dont worry i alredy fixed it. I will a PR after few minutes

**Comment by Ladam0203** [comment]
I presume it just needed Number.isInteger() :)

**Comment by subhranshuchoudhury** [comment]
> I presume it just needed Number.isInteger() :)

😃😁😁
