### ISSUE TITLE
Adding trigonometric functions

### ISSUE THREAD

**Issue by Saurabhlucifer** [DhanushNehru/calculator#67]
I would like to add trigonometric functions such as:
- sin
- -cos
- tan
- cot
- sec
- cosec

Please assign me this issue and also add hacktoberfest label in it.
Thank you.

**Comment by OjashKush** [comment]
https://github.com/DhanushNehru/calculator/pull/62

**Comment by Saurabhlucifer** [comment]
I have created the pull request.
kindly merge it
#70
