### ISSUE TITLE
[bug]: users can enter "++" or any operator one after another.

### ISSUE THREAD

**Issue by subhranshuchoudhury** [DhanushNehru/calculator#71]
Assign this to me. I will create a function which will check the recent operators and stop the user from typing invalid operators one after another.

hacktoberfest

**Comment by SavainB** [comment]
can i work on this ?

**Comment by Zish303** [comment]
I think this issue is still unsolved.
I want to solve this issue for "Hacktoberfest".
Please assign it to me, I will solve it in a week.
