### ISSUE TITLE
Add backspace button.

### ISSUE THREAD

**Issue by SaadOps** [DhanushNehru/calculator#89]
I want to add a backspace button, where do I put it in the UI?
![image](https://user-images.githubusercontent.com/94478736/200862169-742886b7-03cc-4b69-9934-3dfb83707485.png)

**Comment by DhanushNehru** [comment]
Hey @SaadAnsari17 there is a link attached in the project description which has the updated UI, you can check that and add accordingly

**Comment by moein72002** [comment]
pleas check my pull request #94
